Deployment/99/tt/SportsHub/Members/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Members'

urlpatterns = [
   
    path('', views.landing_page, name='landing_page'),
    path('all-users/', views.all_users_view, name='all_users'),
    path('view-fitness-trainers/', views.view_fitness_trainers, name='view_fitness_trainers'),
    path('fitness_user_dashboard/', views.fitness_user_dashboard, name='fitness_user_dashboard'),
    path('sports_user_dashboard/', views.sports_user_dashboard, name='sports_user_dashboard'),
    path('fitness_trainer_dashboard/', views.fitness_trainer_dashboard, name='fitness_trainer_dashboard'),
    path('view_pending_requests/', views.view_pending_requests, name='view_pending_requests'),
    path('approve_reject_request/<int:request_id>/', views.approve_reject_request, name='approve_reject_request'),
    path('select_trainer/', views.select_trainer, name='select_trainer'),
    path('connection_success/', views.connection_success, name='connection_success'),
    path('create_training_plan/', views.create_training_plan, name='create_training_plan'),
    path('training_plan_list/', views.training_plan_list, name='training_plan_list'),
    path('suggest_training_plans/', views.suggest_training_plans, name='suggest_training_plans'),
    path('view_assigned_training_plans/<int:user_id>/', views.view_assigned_training_plans, name='view_assigned_training_plans'),
    path('handle_time_filter/', views.handle_time_filter, name='handle_time_filter'),
    path('accept_training_plan/<int:user_id>/', views.accept_training_plan, name='accept_training_plan'),
    path('reject_training_plan/<int:user_id>/', views.reject_training_plan, name='reject_training_plan'),
    path('create_weekly_plan/', views.create_weekly_plan, name='create_weekly_plan'),
    path('this_weeks_plan/', views.this_weeks_plan, name='this_weeks_plan'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('fitness_users/', views.view_fitness_users, name='view_fitness_users'),
    path('make-reservation/', views.make_reservation, name='make_reservation'),
     path('create-reservation/', views.create_reservation, name='create_reservation'),
    path('get_available_slots/', views.get_available_slots, name='get_available_slots'),
    path('eget_available_slots/', views.eget_available_slots, name='eget_available_slots'),
    path('cereservation/', views.cereservation_page, name='cereservation_page'),
    path('ce_reservation/', views.ce_reservation, name='ce_reservation'),
    path('profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('download_pdf/<path:pdf_path>/', views.download_pdf, name='download_pdf'),

   

]
   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Deployment/99/tt/SportsHub/SportsHub/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include('SportsHubApp.urls')),
    path("users/", include('users.urls')),
    path('members/', include('Members.urls')),
    path('Training/', include('Training.urls')),
    path('plan/', include('plan.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("", include("allauth.urls")),
    path('reset_password/',auth_views.PasswordResetView.as_view(),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Deployment/99/tt/SportsHub/plan/urls.py
from django.contrib import admin
from django.urls import path, include
from plan import views
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
app_name = 'plan'
urlpatterns = [
    path('', views.indexee, name='index'),
    path('all_events/', views.all_events, name='all_events'),
    path('add_event/', views.add_event, name='add_event'),
    path('update/', views.update, name='update'),
    path('remove/', views.remove, name='remove'),


]

Deployment/99/tt/SportsHub/users/urls.py
from django.urls import path
from .views import register  # Import the register view from your app
from . import views
from django.contrib.auth import views as auth_views
from .views import *
app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/',views.custom_login, name='login'),
    path('logout/',views.custom_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('approve-roles/', role_approval_view, name='role_approval'), 
    path('apply-for-role/', role_application_view, name='role_application'), 
    

]

Deployment/99/tt/SportsHub/Members/views.py
# Members/views.py
from django.shortcuts import render

def landing_page(request):
    return render(request, 'landing.html')

from django.shortcuts import render
from .models import  TrainingPlanAssignment, TrainerUserConnection
from .models import CustomUser, FitnessUser, FitnessTrainer, SportsTrainer,WeeklyPlan,DailyWorkout
from SportsHubApp.models import SportsCenter

import matplotlib.pyplot as plt
from io import BytesIO
import base64
from django.shortcuts import render, get_object_or_404
from django.db.models import Sum, Q
from .models import TrainingPlanAssignment, TrainerUserConnection, FitnessUser, FitnessTrainer, SportsTrainer, WeeklyPlan, DailyWorkout, WeeklyFitnessPlan, GymSlot, Reservation, SportsTrainer
from django.utils.timezone import now, timedelta
from django.db.models import Count
from SportsHubApp.models import SportsCenter,Payment

def admin_dashboard(request):
    # Retrieve the last 3 accepted plans
    last_3_accepted_plans = TrainingPlanAssignment.objects.filter(is_accepted=True).order_by('-assigned_date')[:3]

    # Retrieve the last 5 connections made
    last_5_connections = TrainerUserConnection.objects.order_by('-id')[:5]

    # Retrieve the last 3 FitnessUser entries
    last_3_fitness_users = FitnessUser.objects.order_by('-id')[:3]

    # Retrieve the last 3 FitnessTrainer entries
    last_3_fitness_trainers = FitnessTrainer.objects.order_by('-id')[:3]

    # Retrieve the last 3 SportsTrainer entries
    last_3_sports_trainers = SportsTrainer.objects.order_by('-id')[:3]

    # Retrieve the last 3 WeeklyPlan entries
    last_3_weekly_plans = WeeklyPlan.objects.order_by('-id')[:3]

    # Retrieve the last 3 DailyWorkout entries
    last_3_daily_workouts = DailyWorkout.objects.order_by('-id')[:3]

    # Retrieve the last 3 WeeklyFitnessPlan entries
    last_3_weekly_fitness_plans = WeeklyFitnessPlan.objects.order_by('-id')[:3]

    # Retrieve the last 3 GymSlot entries
    last_3_gym_slots = GymSlot.objects.order_by('-id')[:3]

    # Retrieve the last 3 Reservation entries
    last_3_reservations = Reservation.objects.order_by('-id')[:3]

    recent_plans = WeeklyPlan.objects.order_by('-id')[:5]

    if request.method == 'POST':
        sports_center_id = request.POST.get('sports_center')
        sports_trainer_id = request.POST.get('sports_trainer')

        if sports_center_id and sports_trainer_id:
            sports_center = get_object_or_404(SportsCenter, pk=sports_center_id)
            sports_trainer = get_object_or_404(SportsTrainer, pk=sports_trainer_id)

            # Check if the sports_center already has a trainer assigned
            if sports_center.trainer:
                # If assigned, remove the association
                sports_center.trainer = None
                sports_center.save()
            else:
                # If not assigned, associate the trainer with the sports center
                sports_center.trainer = sports_trainer
                sports_center.save()

    sports_centers = SportsCenter.objects.all()
    sports_trainers = SportsTrainer.objects.all()

    labels = ['Category A', 'Category B', 'Category C']
    values = [10, 20, 15]

    sports_centers_without_trainers = SportsCenter.objects.filter(trainer__isnull=True)

# Now, 'sports_centers_without_trainers' contains a queryset of SportsCenter objects without assigned trainers.

    # Encode the plot as base64 for rendering in the template
    
    total_amount_received = Payment.objects.filter(payment_status=Payment.PaymentStatusChoices.SUCCESSFUL).aggregate(Sum('amount'))['amount__sum']

    # If there are no successful payments, set total_amount_received to 0
    total_amount_received = total_amount_received if total_amount_received is not None else 0

    # Extract category names from the queryset
    total_amount_for_reservations = Payment.objects.filter(
        payment_status=Payment.PaymentStatusChoices.SUCCESSFUL,
        reservation__isnull=False
    ).aggregate(Sum('amount'))['amount__sum']

    # If there are no successful payments for reservations, set total_amount_for_reservations to 0
    total_amount_for_reservations = total_amount_for_reservations if total_amount_for_reservations is not None else 0

    # Calculate the total amount for successful payments related to training plans
    total_amount_for_training_plans = Payment.objects.filter(
        payment_status=Payment.PaymentStatusChoices.SUCCESSFUL,
        TrainingPlanAssignment__isnull=False
    ).aggregate(Sum('amount'))['amount__sum']

    # If there are no successful payments for training plans, set total_amount_for_training_plans to 0
    total_amount_for_training_plans = total_amount_for_training_plans if total_amount_for_training_plans is not None else 0

    date_filters = [
        ('All Time', 'all_time'),
        ('Last Month', 'last_month'),
        ('Last Week', 'last_week'),
        ('Last Day', 'last_day'),
    ]
    selected_filter = request.GET.get('time_filter', 'all_time')
   
    context = {
        'last_3_accepted_plans': last_3_accepted_plans,
        'last_5_connections': last_5_connections,
        'last_3_fitness_users': last_3_fitness_users,
        'last_3_fitness_trainers': last_3_fitness_trainers,
        'last_3_sports_trainers': last_3_sports_trainers,
        'last_3_weekly_plans': last_3_weekly_plans,
        'last_3_daily_workouts': last_3_daily_workouts,
        'last_3_weekly_fitness_plans': last_3_weekly_fitness_plans,
        'last_3_gym_slots': last_3_gym_slots,
        'last_3_reservations': last_3_reservations,
        'sports_centers': sports_centers,
        'sports_trainers': sports_trainers,
        'date_filters': date_filters,
        'selected_filter': selected_filter,
        'recent_plans': recent_plans,
        'date_filters': date_filters,
        'sports_centers': sports_centers,
        'sports_centers_without_trainers':sports_centers_without_trainers,
        'total_amount_received': total_amount_received,
        'total_amount_for_reservations': total_amount_for_reservations,
        'total_amount_for_training_plans': total_amount_for_training_plans
        
    }

    return render(request, 'sadmin.html', context)

def handle_time_filter(request):
    selected_filter = request.GET.get('time_filter', 'all_time')

    # Handle the selected filter and apply it to your data
    # You can implement the logic based on the selected_filter value

    # Redirect back to your_existing_view with the updated filter
    return redirect('Members:admin_dashboard')







from django.shortcuts import render
from .models import FitnessUser  # Import your FitnessUser model

def view_fitness_users(request):
    fitness_users = FitnessUser.objects.all()  # Retrieve all Fitness Users
    context = {'fitness_users': fitness_users}
    return render(request, 'view_fitness_users.html', context)


from django.shortcuts import render
from users.models import CustomUser  # Import your CustomUser model

def all_users_view(request):
    # Fetch all users from your CustomUser model
    users = CustomUser.objects.all()

    # Render the template and pass the users to it
    return render(request, 'all_users.html', {'users': users})

# members/views.py

from django.shortcuts import render
from .models import FitnessTrainer

def view_fitness_trainers(request):
    fitness_trainers = FitnessTrainer.objects.all()
    return render(request, 'view_fitness_trainers.html', {'fitness_trainers': fitness_trainers})


# views.py

from django.shortcuts import render

from django.shortcuts import render
from .models import FitnessUser, TrainingPlanAssignment

from django.shortcuts import render
from .models import FitnessUser, TrainingPlanAssignment, TrainerUserConnection

from django.shortcuts import render
from .models import FitnessUser, TrainerUserConnection, TrainingPlanAssignment

from Training.models import NutritionPlan

def fitness_user_dashboard(request):
    # Assuming you have a way to determine the logged-in user, for example, through authentication
    # Replace this line with your logic to get the logged-in user
    logged_in_user = request.user  # Replace with your logic

    # Get the FitnessUser instance associated with the logged-in user
    fitness_user = FitnessUser.objects.get(user=logged_in_user)
    
    # Get the trainer connection for the logged-in user
    trainer_connection = TrainerUserConnection.objects.filter(fitness_user=fitness_user, status='approved').first()
    trainer = trainer_connection.fitness_trainer if trainer_connection else None

    # Get the training plan assignments for the logged-in user
    training_plan_assignments = WorkoutRoutine.objects.filter(creator_user=fitness_user).first()

    # Get the nutrition plan of the user
    nutrition_plan = NutritionPlan.objects.filter(creator_user=fitness_user).first()

    context = {
        'fitness_user': fitness_user,
        'trainer': trainer,
        'training_plan_assignments': training_plan_assignments,
        'nutrition_plan': nutrition_plan,
        
    }
    print("Logged-in User:", logged_in_user)
    print("Fitness User:", fitness_user)
    print("Trainer:", trainer)
    print("Training Plan Assignments:", training_plan_assignments)
    print("Nutrition Plan:", nutrition_plan)
    return render(request, 'fu.html', context)




from django.shortcuts import render
from Members.models import SportsTrainer
from SportsHubApp.models import SReservation,SportscenterSlot



from django.db.models import Count

def sports_user_dashboard(request):
    # Fetch data specific to the logged-in user (assuming the user is a trainer)
    sports_trainer = get_object_or_404(SportsTrainer, user=request.user)
    all_reservations = SReservation.objects.all().order_by('sport__name')

    most_selected_slots = SportscenterSlot.objects.annotate(num_reservations=Count('reservations')).order_by('-num_reservations')
    # Get all SportsCenters where the trainer is the logged-in trainer

Deployment/99/tt/SportsHub/Members/templates/connected_users.html
{% extends "Navbar.html" %}

{% block content %}
<div class="container" style="background-color: rgb(194, 188, 188);">
    <!-- Your content goes here -->
    <h1 class="display-4">My Clients</h1>

    <table class="table table-bordered mt-4">
        <thead>
            <tr>
                <th>Username</th>
                <th>Fitness Goal</th>
                <th>Height (cm)</th>
                <th>Weight (kg)</th>
                <th>View Profile</th>
            </tr>
        </thead>
        <tbody>
            {% for user in connected_users %}
            <tr>
                <td><strong>{{ user.user.username }}</strong></td>
                <td>{{ user.fitness_goal }}</td>
                <td>{{ user.height }}</td>
                <td>{{ user.weight }}</td>
                <td>
                    <!-- Button to trigger the modal -->
                    <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#profileModal{{ user.user.id }}">
                        <i class="fas fa-eye"></i> View Profile
                    </button>
                </td>
            </tr>
            <!-- Profile Modal -->
            <!-- Profile Modal -->
<div class="modal fade" id="profileModal{{ user.user.id }}" tabindex="-1" role="dialog" aria-labelledby="profileModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="profileModalLabel">User Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Display user profile information here -->
                <p><strong>Username:</strong> {{ user.user.username }}</p>
                <p><strong>Email:</strong> {{ user.user.email }}</p>
                <p><strong>Fitness Goal:</strong> {{ user.fitness_goal }}</p>
                <p><strong>Height (cm):</strong> {{ user.height }}</p>
                <p><strong>Weight (kg):</strong> {{ user.weight }}</p>
                <p><strong>Role:</strong> {{ user.user.role }}</p>
                <p><strong>Description:</strong> {{ user.user.description }}</p>
                <!-- Add more user profile details as needed -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <!-- Add more buttons or actions as needed -->
            </div>
        </div>
    </div>
</div>

            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Deployment/99/tt/SportsHub/Members/templates/fu.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'ftco-32x32.png' %}">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha384-KyZXEAg3QhqLMpG8r+VAdr3k6cqGpPjXkbJHIuM/CJ5InAI6fDj4sD6k/KJmJiS" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-training-studio.css' %}">


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link href="{% static 'css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
        crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>

    <style>
        body {
            background-color: #000000; /* Set background color to black */
        }

        .card {
            background-color: #000000;
            border: 2px solid #ffffff;
            color: #ffffff;
            margin-bottom: 20px; /* Adjust spacing between cards */
        }

        .card-body {
            padding: 20px;
        }

        .card-title {
            color: #ffffff;
        }

        .main-nav {
            background-color: #000000; /* Set background color for the navigation bar */
        }
    </style>
</head>

<body>
    <header class="header-area   main-nav">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">

                        <a href="index.html" class="logo">Sports<em>Hub</em></a>

                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url 'index' %}">Home</a></li>



                            <li class="scroll-to-section"><a href="{% url 'users:logout' %}"
                                    class="nav-link">Logout</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <!-- Content Block -->
    <div class="container mt-4">
        <br>
        <br>
        <br>
        {% block content %}
        <div class="container mt-5">
            <h1 class="display-4">Welcome</h1>

            <div class="row row-cols-1 row-cols-md-2 g-4">
                <!-- User Profile Section -->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">User Information</h5>
                        <div class="row">
                            <div class="col-sm-6">
                                <p><strong>UserName:</strong> {{ fitness_user.user.username }}</p>
                                <p><strong>Email:</strong> {{ fitness_user.user.email }}</p>
                            </div>
                            <div class="col-sm-6">
                                <p><strong>Height:</strong> {{ fitness_user.height }} cm</p>
                                <p><strong>Weight:</strong> {{ fitness_user.weight }} kg</p>
                            </div>
                        </div>
                    </div>
                </div>
                
                </div>
                



                <!-- Trainer Information Section -->
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Trainer Information</h3>
                            {% if trainer %}
                            <div class="card-text">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item"><strong>Name:</strong> {{ trainer.user.first_name }}</li>
                                    <li class="list-group-item"><strong>Email:</strong> {{ trainer.user.email }}</li>
                                    <li class="list-group-item"><strong>Experience:</strong> {{ trainer.experience }} years</li>
                                </ul>
                            </div>
                            {% else %}
                            <p class="card-text">You do not have a connected trainer at the moment.</p>
                            {% endif %}
                        </div>
                    </div>
                    
                </div>

                <!-- Your Workout Routine Assignment Section -->
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Your Workout Routine Assignment</h3>
                            {% if training_plan_assignments %}
                            <strong>Name:</strong> {{ training_plan_assignments.name }}<br>
                            <strong>Description:</strong> {{ training_plan_assignments.description }}<br>
                            <strong>Exercises:</strong>
                            <ul>
                                {% for exercise in training_plan_assignments.exercises.all %}
                                <li>{{ exercise.name }}</li>
                                {% endfor %}
                            </ul>
                            {% else %}
                            <p>You don't have any workout routine assignments yet.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <!-- Your Nutrition Plan Section -->
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Your Nutrition Plan</h3>
                            {% if nutrition_plan %}
                            <strong>Name:</strong> {{ nutrition_plan.name }}<br>
                            <strong>Description:</strong> {{ nutrition_plan.description }}<br>
                            <strong>Items:</strong>
                            <ul>
                                {% for item in nutrition_plan.items.all %}
                                <li>{{ item.name }}</li>
                                {% endfor %}
                            </ul>
                            {% else %}
                            <p>You don't have any assigned nutrition plan yet.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

Deployment/99/tt/SportsHub/Members/templates/list_equipment.html
{% extends 'Navbar.html' %}

{% block content %}
    <h1>Available Equipment</h1>
    <ul>
        {% for item in equipment %}
            <li>
                <strong>{{ item.name }}</strong> - {{ item.description }}
                <a href="{% url 'Members:make_reservation' %}">Make Reservation</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

Deployment/99/tt/SportsHub/Members/templates/training_plan_list.html
{% extends "Navbar.html" %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Training Plans List</h1>
    
    <h3>Training Plans Created by You</h3>
    {% if training_plans %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Plan Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Amount</th> <!-- Add this column -->
                </tr>
            </thead>
            <tbody>
                {% for plan in training_plans %}
                    <tr>
                        <td>{{ plan.plan_name }}</td>
                        <td>{{ plan.description }}</td>
                        <td>{{ plan.duration }} days</td>
                        <td>${{ plan.amount }}</td> <!-- Display the amount -->
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No training plans found.</p>
    {% endif %}
    
    <!-- Add a link to create a new training plan -->
    <a href="{% url 'Members:create_training_plan' %}" class="btn btn-primary">Create New Training Plan</a>
</div>
{% endblock %}

Deployment/99/tt/SportsHub/Members/templates/update_weekly_workout_plan.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Weekly Workout Plan</button>
</form>

Deployment/99/tt/SportsHub/Members/templates/view_assigned_training_plans.html
{% extends "Navbar2.html" %}

{% block content %}
    <div class="container mt-5">
        <h1>Assigned Training Plans</h1>
    </div>

    <div class="container mt-3">
        <div class="row">
            {% for assignment in assignments %}
          
                    <div class="col-md-6 mb-4">
                        <div class="card" style="background-color: #264653; color: #FFFFA5; padding: 10px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);">
                            <div class="card-body">
                                <h4 class="card-title" style="font-size: 1.25rem; font-weight: bold;">Plan Name: {{ assignment.plan.plan_name }}</h4>
                                <p class="card-text">Assigned by: {{ assignment.assigned_by.user.username }}</p>
                                <p class="card-text">Assigned Date: {{ assignment.assigned_date }}</p>
                                <p class="card-text">Plan Description: {{ assignment.plan.description }}</p>
                                <p class="card-text"><span class="badge" style="background-color: #FFA500; color: #000;">Price: RS.{{ assignment.plan.amount }}</span></p>
                                <p class="card-text mt-3">Status: {% if assignment.is_accepted %}<span class="badge" style="background-color: #28a745; color: #fff;">Accepted</span>{% else %}<span class="badge" style="background-color: #FFA500; color: #000;">Pending</span>{% endif %}</p>
                            </div>
                            <div class="card-footer text-center">
                                {% if not assignment.is_accepted %}
                                    <form method="post" action="{% url 'Members:accept_training_plan' user_id=fitness_user.user.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="assignment_id" value="{{ assignment.id }}">
                                        <button type="submit" class="btn btn-success btn-lg btn-block" style="background-color: #28a745;">Accept</button>
                                    </form>
                    
                                    <form method="post" action="{% url 'Members:reject_training_plan' user_id=fitness_user.user.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="assignment_id" value="{{ assignment.id }}">
                                        <button type="submit" class="btn btn-danger btn-lg btn-block" style="background-color: #dc3545;">Reject</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    
            
            {% endfor %}
        </div>
    </div>
{% endblock %}