Deployment/99/tt/SportsHub/Members/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Members'

urlpatterns = [
   
    path('', views.landing_page, name='landing_page'),
    path('all-users/', views.all_users_view, name='all_users'),
    path('view-fitness-trainers/', views.view_fitness_trainers, name='view_fitness_trainers'),
    path('fitness_user_dashboard/', views.fitness_user_dashboard, name='fitness_user_dashboard'),
    path('sports_user_dashboard/', views.sports_user_dashboard, name='sports_user_dashboard'),
    path('fitness_trainer_dashboard/', views.fitness_trainer_dashboard, name='fitness_trainer_dashboard'),
    path('view_pending_requests/', views.view_pending_requests, name='view_pending_requests'),
    path('approve_reject_request/<int:request_id>/', views.approve_reject_request, name='approve_reject_request'),
    path('select_trainer/', views.select_trainer, name='select_trainer'),
    path('connection_success/', views.connection_success, name='connection_success'),
    path('create_training_plan/', views.create_training_plan, name='create_training_plan'),
    path('training_plan_list/', views.training_plan_list, name='training_plan_list'),
    path('suggest_training_plans/', views.suggest_training_plans, name='suggest_training_plans'),
    path('view_assigned_training_plans/<int:user_id>/', views.view_assigned_training_plans, name='view_assigned_training_plans'),
    path('handle_time_filter/', views.handle_time_filter, name='handle_time_filter'),
    path('accept_training_plan/<int:user_id>/', views.accept_training_plan, name='accept_training_plan'),
    path('reject_training_plan/<int:user_id>/', views.reject_training_plan, name='reject_training_plan'),
    path('create_weekly_plan/', views.create_weekly_plan, name='create_weekly_plan'),
    path('this_weeks_plan/', views.this_weeks_plan, name='this_weeks_plan'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('fitness_users/', views.view_fitness_users, name='view_fitness_users'),
    path('make-reservation/', views.make_reservation, name='make_reservation'),
     path('create-reservation/', views.create_reservation, name='create_reservation'),
    path('get_available_slots/', views.get_available_slots, name='get_available_slots'),
    path('eget_available_slots/', views.eget_available_slots, name='eget_available_slots'),
    path('cereservation/', views.cereservation_page, name='cereservation_page'),
    path('ce_reservation/', views.ce_reservation, name='ce_reservation'),
    path('profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('download_pdf/<path:pdf_path>/', views.download_pdf, name='download_pdf'),

   

]
   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Deployment/99/tt/SportsHub/SportsHub/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include('SportsHubApp.urls')),
    path("users/", include('users.urls')),
    path('members/', include('Members.urls')),
    path('Training/', include('Training.urls')),
    path('plan/', include('plan.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("", include("allauth.urls")),
    path('reset_password/',auth_views.PasswordResetView.as_view(),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Deployment/99/tt/SportsHub/Training/urls.py
# connect/urls.py

from django.urls import path
from . import views
from . import views

app_name = 'Training'
urlpatterns = [
    # ... Your other URL patterns ...
    path('choose_trainer/', views.choose_trainer, name='choose_trainer'),
    path('connection_list/', views.connection_list, name='connection_list'),

    path('render-my-template/', views.render_my_template, name='render_my_template'),
    path('workout_routines/', views.workout_routines, name='workout_routines'),
    path('create_routine/', views.create_routine, name='create_routine'),
    path('user_workout_routines/', views.user_workout_routines, name='user_workout_routines'),
    path('trainer_previous_assignments/', views.trainer_previous_assignments, name='trainer_previous_assignments'),
    path('assign_nutrition_plan/<int:user_id>/', views.assign_nutrition_plan, name='assign_nutrition_plan'),
    path('edit_nutrition_plan/<int:nutrition_plan_id>/', views.edit_nutrition_plan, name='edit_nutrition_plan'),
    path('delete_nutrition_plan/<int:nutrition_plan_id>/', views.delete_nutrition_plan, name='delete_nutrition_plan'), 
    path('assign_workout_routine/<int:user_id>/', views.assign_workout_routine, name='assign_workout_routine'),
    path('edit_workout_routine/<int:workout_routine_id>/', views.edit_workout_routine, name='edit_workout_routine'),
    path('delete_workout_routine/<int:workout_routine_id>/', views.delete_workout_routine, name='delete_workout_routine'),






    

]

Deployment/99/tt/SportsHub/plan/urls.py
from django.contrib import admin
from django.urls import path, include
from plan import views
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
app_name = 'plan'
urlpatterns = [
    path('', views.indexee, name='index'),
    path('all_events/', views.all_events, name='all_events'),
    path('add_event/', views.add_event, name='add_event'),
    path('update/', views.update, name='update'),
    path('remove/', views.remove, name='remove'),


]

Deployment/99/tt/SportsHub/users/urls.py
from django.urls import path
from .views import register  # Import the register view from your app
from . import views
from django.contrib.auth import views as auth_views
from .views import *
app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/',views.custom_login, name='login'),
    path('logout/',views.custom_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('approve-roles/', role_approval_view, name='role_approval'), 
    path('apply-for-role/', role_application_view, name='role_application'), 
    

]

Deployment/99/tt/SportsHub/Training/views.py
# Import statements
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import UserTrainerConnection, WorkoutRoutine, Exercise
from .forms import WorkoutRoutineForm, NutritionPlanAssignmentForm,UserTrainerConnectionForm
from Members.models import FitnessTrainer,FitnessUser
from datetime import date


from django.http import JsonResponse
from django.db import transaction
from django.contrib.auth.models import User

def choose_trainer(request):
    # Check if the user has existing connections
    existing_connections = UserTrainerConnection.objects.filter(user=request.user)
    
    # If the user has no existing connections, display available trainers
    if not existing_connections:
        trainers = FitnessTrainer.objects.all()  # Query all available trainers
        if request.method == 'POST':
            form = UserTrainerConnectionForm(request.POST)
            if form.is_valid():
                connection = form.save(commit=False)
                connection.user = request.user
                connection.save()
                return redirect('index')  # Redirect to connection list view
        else:
            form = UserTrainerConnectionForm()
        
        return render(request, 'choose_trainer.html', {'trainers': trainers, 'form': form})

    # If the user already has connections, redirect to the connection list view
    return redirect('connection_list')



def choose_trainer(request):
    # Check if the user has existing connections
    existing_connections = UserTrainerConnection.objects.filter(user=request.user)

    if request.method == 'POST':
        form = UserTrainerConnectionForm(request.POST)
        if form.is_valid():
            connection = form.save(commit=False)
            connection.user = request.user
            connection.save()
            return redirect('connection_list')  # Redirect to the connection list view
    else:
        form = UserTrainerConnectionForm()

    # If the user has no existing connections, display available trainers
    if not existing_connections:
        trainers = FitnessTrainer.objects.all()
        return render(request, 'choose_trainer.html', {'trainers': trainers, 'form': form})

    # If the user already has connections, redirect to the connection list view
    return redirect('connection_list')

@login_required
def connection_list(request):
    # Query the user's connections
    connections = UserTrainerConnection.objects.filter(user=request.user)
    
    return render(request, 'connection_list.html', {'connections': connections})



from django.shortcuts import render

def render_my_template(request):
    # Your view logic here (if needed)

    # Render the HTML template and return the response
    return render(request, 's.html')





# Function to calculate angle between three points


def workout_routines(request):
    # Assuming you have a way to identify the current user
    user = request.user

    # Get the user's active trainer connection
    connection = get_object_or_404(UserTrainerConnection, user=user, end_date__gte=date.today())

    # Get the workout routines associated with the user's trainer
    routines = WorkoutRoutine.objects.filter(connection=connection)

    return render(request, 'workout_routines.html', {'routines': routines})


@login_required
def workout_routines(request):
    trainer = request.user.fitnesstrainer  # Assuming the user is a fitness trainer

    # Get the trainer's active connection (without date constraints)
    connection = FitnessUser.objects.filter(traineruserconnection__fitness_trainer=trainer)

    # Get the workout routines associated with the user's trainer
    routines = WorkoutRoutine.objects.all()

    return render(request, 'workout_routines.html', {'routines': routines})


@login_required
def create_routine(request):
    trainer = request.user.fitnesstrainer  # Assuming the user is a fitness trainer

    # Get the trainer's active connection (without date constraints)
    connection = FitnessUser.objects.filter(traineruserconnection__fitness_trainer=trainer)
    

    if connection is None:
        # Handle the case where there is no active trainer connection
        return render(request, 'xreservation.html')

    if request.method == 'POST':
        form = WorkoutRoutineForm(request.POST)
        if form.is_valid():
            routine = form.save(commit=False)

            with transaction.atomic():
                routine.creator_trainer = trainer
                
                routine.save()

                routine.exercises.set(form.cleaned_data['exercises'])
            return redirect('Members:fitness_trainer_dashboard')
    else:
        form = WorkoutRoutineForm()

    return render(request, 'create_routine.html', {'form': form})


@login_required
def user_workout_routines(request):
    # Get the currently logged-in user
    fitness_user = request.user.fitnessuser

    # Get all workout routines assigned to the logged-in user
    assigned_workout_routines = WorkoutRoutine.objects.filter(creator_user=fitness_user)

    return render(request, 'user_workout_routines.html', {'assigned_workout_routines': assigned_workout_routines})

@login_required
def trainer_previous_assignments(request):
    # Assuming the user is a fitness trainer
    trainer = request.user.fitnesstrainer

    # Get all workout routines created by the trainer
    previous_assignments = WorkoutRoutine.objects.filter(creator_trainer=trainer)

    return render(request, 'trainer_previous_assignments.html', {'previous_assignments': previous_assignments})
from django.contrib.auth import get_user_model 
CustomUser = get_user_model()


from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import CustomUser, FitnessUser, FitnessTrainer
from .forms import NutritionPlanAssignmentForm
from django.db import transaction

@login_required
def assign_nutrition_plan(request, user_id):
    trainer = request.user.fitnesstrainer

    user = get_object_or_404(CustomUser, id=user_id)

    connection = FitnessUser.objects.filter(traineruserconnection__fitness_trainer=trainer, user=user).first()

    if connection is None:
        return render(request, 'xreservation.html')

    if request.method == 'POST':
        form = NutritionPlanAssignmentForm(request.POST, trainer=trainer, user=user)
        if form.is_valid():
            with transaction.atomic():
                assignment = form.save(commit=False)
                assignment.creator_trainer = trainer
                assignment.save()
                assignment.items.set(form.cleaned_data['items'])
            return redirect('Members:fitness_trainer_dashboard')
    else:
        form = NutritionPlanAssignmentForm(trainer=trainer, user=user)

    return render(request, 'assign_nutrition_plan.html', {'form': form, 'user': user})


# views.py

from django.shortcuts import render, get_object_or_404, redirect
from .models import NutritionPlan
from .forms import NutritionPlanAssignmentForm

# views.py

from django.shortcuts import render, get_object_or_404, redirect
from .models import NutritionPlan
from .forms import NutritionPlanAssignmentForm
from django.contrib.auth.decorators import login_required

# views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
from .models import NutritionPlan
from .forms import NutritionPlanAssignmentForm
# views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
from .models import NutritionPlan
from .forms import NutritionPlanAssignmentForm

@login_required
def edit_nutrition_plan(request, nutrition_plan_id):
    nutrition_plan = get_object_or_404(NutritionPlan, id=nutrition_plan_id)

    # Check if the logged-in user is allowed to edit this nutrition plan
    if request.user != nutrition_plan.creator_trainer.user:
        raise PermissionDenied("You do not have permission to edit this nutrition plan.")

    # Handle form submission
    if request.method == 'POST':
        form = NutritionPlanAssignmentForm(request.POST, instance=nutrition_plan)

        # Check if the form is valid
        if form.is_valid():
            # Save the form data to the database
            instance = form.save()

            # Optionally, handle adding items to the plan
            item_ids = request.POST.getlist('items')  # Assuming 'items' is the name of the items field in the form
            instance.items.set(item_ids)  # Set the selected items for the nutrition plan

            return redirect('Members:fitness_trainer_dashboard')
        else:
            # Print form errors if the form is not valid
            print("Form is not valid:", form.errors)

    else:
        # For GET requests, create a form instance with the existing nutrition_plan data
        form = NutritionPlanAssignmentForm(instance=nutrition_plan)

    # Render the template with the form and nutrition_plan data
    return render(request, 'edit_nutrition_plan.html', {'form': form, 'nutrition_plan': nutrition_plan})




@login_required
def delete_nutrition_plan(request, nutrition_plan_id):
    nutrition_plan = get_object_or_404(NutritionPlan, id=nutrition_plan_id)

    # Check if the logged-in user is allowed to delete this nutrition plan
    # You might want to customize this based on your business logic
    if request.user != nutrition_plan.creator_trainer.user:
        return render(request, 'permission_denied.html')

    if request.method == 'POST':
        nutrition_plan.delete()
        return redirect('Members:fitness_trainer_dashboard')

    return render(request, 'delete_nutrition_plan.html', {'nutrition_plan': nutrition_plan})








from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def view_nutrition_plan(request):

Deployment/99/tt/SportsHub/Training/templates/assign_nutrition_plan.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html>

<head>
   <meta charset="utf-8"> 
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <title></title>
   <meta name="description" content="">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="shortcut icon" href="{% static 'ftco-32x32.png' %}">

   <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+VAdr3k6cqGpPjXkbJHIuM/CJ5InAI6fDj4sD6k/KJmJiS" crossorigin="anonymous">
 
   <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

   <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-training-studio.css' %}">
    
 
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
 
   <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
 
   <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
 
   <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
 
   <link rel="stylesheet" href="{% static 'css/aos.css' %}">
   <link href="{% static 'css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">
 
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"></script>

   <style>
      .soul-logo { 
         mix-blend-mode: color-burn;
      }

      .placform::placeholder {
         position: absolute;
         left: 10px;
      }


      label {
         font-weight: bold;
      }
      body {
        background-color: #f2f2f2; /* Light grey background color */
    }
   </style>
</head>


      <header class="header-area header-sticky"  style="background:  #000000;">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">Sports<em>Hub</em></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                          <li class="scroll-to-section"><a href="{% url 'index' %}" >Home</a></li>
                          <li class="scroll-to-section"><a href="{% url 'Members:create_weekly_plan' %}">WP</a></li>
                          <li class="scroll-to-section"><a href="{% url 'Members:create_training_plan' %}">Create Plan</a></li>
                          <li class="scroll-to-section"><a href="{% url 'Members:cereservation_page' %}" >Equipment</a></li>
  
                          <li><a href="{% url 'Training:create_routine'  %}">tte</a></li>
                          <!-- Include this button wherever you want in your template -->
  
  
                          <li class="scroll-to-section"><a href="{% url 'Members:make_reservation'  %}">Make Reservations</a></li> 
                          <li class="scroll-to-section"><a href="{% url 'Members:suggest_training_plans' %}">Training Plans</a></li>
                            
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
<br>
<br>

    <!-- Content Block -->

<!-- create_routine.html -->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card" style="background-color: #ffffff;">
                <div class="card-body p-4 p-lg-5 text-black">
                    <h2 class="fw-normal mb-3 pb-3 text-center" style="letter-spacing: 1px; font-weight:bold; color:#bc0505;">Create Plan</h2>
                    <form method="post" class="needs-validation" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger">Create Plan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


 

    <!-- Bootstrap and JavaScript links (unchanged) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Deployment/99/tt/SportsHub/Training/templates/choose_trainer.html
<!-- connect/choose_trainer.html -->


{% block content %}
  <h2>Choose a Trainer</h2>
  <form method="post">
    {% csrf_token %}
    <label for="trainer">Select a Trainer:</label>
    <select name="trainer" id="trainer">
      {% for trainer in trainers %}
        <option value="{{ trainer.id }}">{{ trainer.user.username }}</option>
      {% endfor %}
    </select>
    <button type="submit">Choose</button>
  </form>
{% endblock %}

<a href="{% url 'Training:connection_list' %}" class="btn btn-secondary">View Your Connections</a>

Deployment/99/tt/SportsHub/Training/templates/create_routine.html
<!-- create_routine.html -->
<!-- workout_routines.html -->
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html>

<head>
   <meta charset="utf-8"> 
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <title></title>
   <meta name="description" content="">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="shortcut icon" href="{% static 'ftco-32x32.png' %}">

   <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+VAdr3k6cqGpPjXkbJHIuM/CJ5InAI6fDj4sD6k/KJmJiS" crossorigin="anonymous">
 
   <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

   <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-training-studio.css' %}">
    
 
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
 
   <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
 
   <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
 
   <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
 
   <link rel="stylesheet" href="{% static 'css/aos.css' %}">
   <link href="{% static 'css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">
 
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"></script>

   <style>
      .soul-logo { 
         mix-blend-mode: color-burn;
      }

      .placform::placeholder {
         position: absolute;
         left: 10px;
      }


      label {
         font-weight: bold;
      }
      body {
        background-color: #f2f2f2; /* Light grey background color */
    }
   </style>
</head>


      <header class="header-area header-sticky"  style="background:  #000000;">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">Sports<em>Hub</em></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url 'index' %}">Home</a>
                            <li class="scroll-to-section"><a href="{% url 'Members:select_trainer' %}">Select Trainer</a></li>
                            <li class="scroll-to-section"><a href="{% url 'Members:view_assigned_training_plans' user.id %}">My Plan</a></li>
                            <li class="scroll-to-section"><a href="{% url 'Members:this_weeks_plan' %}">This Week's Plan</a></li>
                        
                            <li><a href="{% url 'Training:create_routine'  %}">tte</a></li>
                            <li class="scroll-to-section"><a href="{% url 'Training:render_my_template' %}" >Train with ZIZU</a></li> 
                            
                            <li class="scroll-to-section"><a href="{% url 'users:logout' %}" class="nav-link">Logout</a></li> 
                            
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
<br>
<br>

    <!-- Content Block -->

<!-- create_routine.html -->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card" style="background-color: #ffffff;">
                <div class="card-body p-4 p-lg-5 text-black">
                    <h2 class="fw-normal mb-3 pb-3 text-center" style="letter-spacing: 1px; font-weight:bold; color:#bc0505;">Create Plan</h2>
                    <form method="post" class="needs-validation" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger">Create Plan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


 

    <!-- Bootstrap and JavaScript links (unchanged) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>